/**
 * AIInsightsDrawer — slide-out panel from the right edge with an
 * AI-generated narrative for the current page context.
 *
 * Behaviour:
 *   - Trigger lives in the Topbar (sparkles icon next to the dark-mode
 *     toggle). Visible only on routes where AI context makes sense
 *     (home + /phd + /bondhu).
 *   - On open, fetches the appropriate endpoint:
 *       /              → /api/dashboard/programme-summary/
 *       /phd           → /api/dashboard/org-summary/?partner=PHD
 *       /bondhu        → /api/dashboard/org-summary/?partner=Bandhu
 *   - Loading shows a shimmering skeleton; errors show a retry button.
 *   - Drawer closes via X, click outside, or Escape.
 *   - Animations respect prefers-reduced-motion.
 *
 * Narrative source provenance is surfaced as a small tag at the bottom
 * (ai / template / ai_validation_failed / etc) so users can tell when
 * the LLM was bypassed in favour of the deterministic template.
 */
import { useEffect, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { motion, AnimatePresence, useReducedMotion } from 'motion/react'
import { Sparkles, X, RefreshCw, AlertCircle } from 'lucide-react'
import { api } from '@/api/client'

interface InsightsResponse {
  ai_summary: string
  period: string
  generated_at: string
  narrative_source?: string
}

function endpointForPath(pathname: string): { url: string; scope: string } | null {
  if (pathname === '/')          return { url: '/dashboard/programme-summary/',        scope: 'programme' }
  if (pathname === '/phd')       return { url: '/dashboard/org-summary/?partner=PHD',  scope: 'PHD'       }
  if (pathname === '/bondhu')    return { url: '/dashboard/org-summary/?partner=Bandhu', scope: 'Bandhu'  }
  return null
}

export function AIInsightsDrawer() {
  const { t } = useTranslation()
  const { pathname } = useLocation()
  const reduce = useReducedMotion()
  const [open, setOpen] = useState(false)
  const [data, setData] = useState<InsightsResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const endpoint = endpointForPath(pathname)

  const fetchInsights = async () => {
    if (!endpoint) return
    setLoading(true)
    setError(null)
    try {
      const resp = await api.get<InsightsResponse>(endpoint.url)
      setData(resp.data)
    } catch (e: any) {
      setError(e?.response?.data?.detail || 'Could not load AI insights.')
    } finally {
      setLoading(false)
    }
  }

  // Refetch when drawer opens or route changes while open.
  useEffect(() => {
    if (open) fetchInsights()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, pathname])

  // Close on Escape.
  useEffect(() => {
    if (!open) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [open])

  // Don't render the trigger on routes that have no AI context.
  if (!endpoint) return null

  const sourceLabel = (src?: string) => {
    switch (src) {
      case 'ai': return t('aiDrawer.sourceAI', { defaultValue: 'Generated by Groq · LLaMA 3.3 70B' })
      case 'template': return t('aiDrawer.sourceTemplate', { defaultValue: 'Deterministic template (AI disabled or insufficient data)' })
      case 'ai_validation_failed': return t('aiDrawer.sourceValidation', { defaultValue: 'AI fell back to template (figure validation failed)' })
      case 'ai_api_error': return t('aiDrawer.sourceApiErr', { defaultValue: 'AI fell back to template (API error)' })
      case 'insufficient_data': return t('aiDrawer.sourceSparse', { defaultValue: 'Deterministic template (data sparse this period)' })
      default: return ''
    }
  }

  return (
    <>
      {/* Trigger — sparkles icon, same pill shape as language + dark toggles */}
      <button
        type="button"
        onClick={() => setOpen(true)}
        title={t('aiDrawer.openTitle', { defaultValue: 'AI insights for this page' })}
        aria-label={t('aiDrawer.openTitle', { defaultValue: 'AI insights for this page' })}
        className="lang-toggle-btn"
        style={{
          display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
          width: 32, height: 32, minWidth: 32, minHeight: 32,
          borderRadius: 999,
          background: 'var(--surface-2)',
          border: '1px solid var(--hair)',
          color: 'var(--unfpa)',
          cursor: 'pointer',
        }}
      >
        <Sparkles size={14} />
      </button>

      <AnimatePresence mode="wait">
        {open && (
          <>
            {/* Backdrop */}
            <motion.div
              key="ai-backdrop"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0, transition: { duration: 0.15 } }}
              transition={{ duration: 0.2 }}
              onClick={() => setOpen(false)}
              style={{
                position: 'fixed', inset: 0, zIndex: 200,
                background: 'rgba(19, 22, 25, 0.35)',
                // Targeted glassmorphism — backdrop-blur on the scrim
                // only, never on content. Stays within the UNFPA kit
                // (foundation is open/white; this is the OVERLAY).
                backdropFilter: 'blur(8px) saturate(1.1)',
                WebkitBackdropFilter: 'blur(8px) saturate(1.1)',
              }}
            />

            {/* Panel — slide from right */}
            <motion.aside
              key="ai-panel"
              role="dialog"
              aria-modal="true"
              aria-label="AI insights"
              initial={{ x: reduce ? 0 : '100%', opacity: reduce ? 0 : 1 }}
              animate={{ x: 0, opacity: 1, transition: { duration: 0.32, ease: [0.22, 1, 0.36, 1] } }}
              exit={{ x: reduce ? 0 : '100%', opacity: reduce ? 0 : 1, transition: { duration: 0.2, ease: [0.4, 0, 1, 1] } }}
              style={{
                position: 'fixed', top: 0, right: 0,
                width: 'min(460px, 92vw)', height: '100vh',
                background: 'var(--surface)',
                borderLeft: '1px solid var(--hair)',
                boxShadow: 'var(--sh-3)',
                zIndex: 201,
                display: 'flex',
                flexDirection: 'column',
              }}
            >
              {/* Header */}
              <header style={{
                padding: '18px 22px',
                borderBottom: '1px solid var(--hair)',
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <span style={{
                    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                    width: 28, height: 28, borderRadius: 8,
                    background: 'rgba(249, 96, 0, 0.10)',
                    color: 'var(--unfpa)',
                  }}>
                    <Sparkles size={15} />
                  </span>
                  <div>
                    <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--ink)' }}>
                      {t('aiDrawer.title', { defaultValue: 'AI Insights' })}
                    </div>
                    <div style={{ fontSize: 11, color: 'var(--muted)' }}>
                      {endpoint.scope === 'programme'
                        ? t('aiDrawer.scopeProgramme', { defaultValue: 'Programme-wide · all three partners' })
                        : t('aiDrawer.scopePartner', { defaultValue: '{{partner}} dashboard', partner: endpoint.scope })}
                    </div>
                  </div>
                </div>
                <div style={{ display: 'flex', gap: 6 }}>
                  <button
                    onClick={fetchInsights}
                    title={t('aiDrawer.refresh', { defaultValue: 'Refresh' })}
                    disabled={loading}
                    className="lang-toggle-btn"
                    style={{
                      display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                      width: 30, height: 30, borderRadius: 999,
                      background: 'transparent', border: '1px solid var(--hair)',
                      color: 'var(--ink-3)', cursor: loading ? 'wait' : 'pointer',
                    }}
                  >
                    <RefreshCw size={13} className={loading ? 'spin' : ''} />
                  </button>
                  <button
                    onClick={() => setOpen(false)}
                    title={t('aiDrawer.close', { defaultValue: 'Close' })}
                    className="lang-toggle-btn"
                    style={{
                      display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                      width: 30, height: 30, borderRadius: 999,
                      background: 'transparent', border: '1px solid var(--hair)',
                      color: 'var(--ink-3)', cursor: 'pointer',
                    }}
                  >
                    <X size={14} />
                  </button>
                </div>
              </header>

              {/* Body */}
              <div style={{
                flex: 1, overflowY: 'auto', padding: '22px',
                display: 'flex', flexDirection: 'column', gap: 16,
              }}>
                {loading && (
                  <>
                    <div className="ai-skeleton" style={{ height: 14, width: '95%' }} />
                    <div className="ai-skeleton" style={{ height: 14, width: '88%' }} />
                    <div className="ai-skeleton" style={{ height: 14, width: '70%' }} />
                    <div style={{ height: 12 }} />
                    <div className="ai-skeleton" style={{ height: 14, width: '92%' }} />
                    <div className="ai-skeleton" style={{ height: 14, width: '60%' }} />
                  </>
                )}

                {!loading && error && (
                  <div style={{
                    display: 'flex', alignItems: 'flex-start', gap: 10,
                    padding: 14, borderRadius: 10,
                    background: 'rgba(241, 15, 69, 0.05)',
                    border: '1px solid rgba(241, 15, 69, 0.18)',
                    color: '#9A1131', fontSize: 13,
                  }}>
                    <AlertCircle size={16} style={{ flexShrink: 0, marginTop: 1 }} />
                    <div style={{ flex: 1 }}>
                      <div style={{ fontWeight: 600, marginBottom: 4 }}>
                        {t('aiDrawer.errorTitle', { defaultValue: 'Could not load insights' })}
                      </div>
                      <div style={{ color: 'var(--ink-3)', fontSize: 12 }}>{error}</div>
                      <button
                        onClick={fetchInsights}
                        style={{
                          marginTop: 10, padding: '6px 12px', fontSize: 12,
                          borderRadius: 6, border: '1px solid var(--hair)',
                          background: 'var(--surface)', color: 'var(--ink)',
                          cursor: 'pointer',
                        }}
                      >
                        {t('aiDrawer.retry', { defaultValue: 'Retry' })}
                      </button>
                    </div>
                  </div>
                )}

                {!loading && !error && data && (
                  <>
                    <div style={{
                      fontSize: 10.5, color: 'var(--muted)', fontWeight: 600,
                      textTransform: 'uppercase', letterSpacing: '0.08em',
                    }}>
                      {data.period}
                    </div>
                    <div style={{
                      fontSize: 14.5, lineHeight: 1.6, color: 'var(--ink)',
                      whiteSpace: 'pre-wrap',
                      textWrap: 'pretty',
                    } as React.CSSProperties}>
                      {data.ai_summary}
                    </div>
                  </>
                )}
              </div>

              {/* Footer */}
              <footer style={{
                padding: '12px 22px', borderTop: '1px solid var(--hair)',
                fontSize: 11, color: 'var(--muted)',
                fontVariantNumeric: 'tabular-nums',
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                gap: 12,
              }}>
                <span style={{ flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis' }}>
                  {data?.narrative_source ? sourceLabel(data.narrative_source) : t('aiDrawer.footerHint', {
                    defaultValue: 'AI-assisted summary · refreshes on demand',
                  })}
                </span>
                {data?.generated_at && (
                  <span style={{ flexShrink: 0 }}>
                    {new Date(data.generated_at).toLocaleTimeString('en-GB', {
                      hour: '2-digit', minute: '2-digit',
                    })}
                  </span>
                )}
              </footer>
            </motion.aside>
          </>
        )}
      </AnimatePresence>

      {/* Spinner + skeleton styles (drawer-local) */}
      <style>{`
        .ai-skeleton {
          background: linear-gradient(90deg, var(--surface-2) 0%, var(--surface-3) 50%, var(--surface-2) 100%);
          background-size: 200% 100%;
          border-radius: 6px;
          animation: aiShimmer 1.4s ease-in-out infinite;
        }
        @keyframes aiShimmer {
          0%   { background-position: 200% 0; }
          100% { background-position: -200% 0; }
        }
        .lang-toggle-btn .spin {
          animation: aiSpin 800ms linear infinite;
        }
        @keyframes aiSpin {
          to { transform: rotate(360deg); }
        }
      `}</style>
    </>
  )
}
