# Generated by Django 5.2.1 on 2026-05-23 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MPDSRCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, unique=True
                    ),
                ),
                ("partner", models.CharField(db_index=True, max_length=20)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("date_of_death", models.DateField()),
                (
                    "death_type",
                    models.CharField(
                        choices=[
                            ("maternal", "Maternal Death"),
                            ("perinatal", "Perinatal Death"),
                        ],
                        db_index=True,
                        default="maternal",
                        max_length=20,
                    ),
                ),
                ("cause_of_death", models.CharField(blank=True, max_length=300)),
                ("facility_name", models.CharField(blank=True, max_length=200)),
                ("age_years", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("under_review", "Under Review"),
                            ("committee_review", "Committee Review"),
                            ("action_plan_drafted", "Action Plan Drafted"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="reported",
                        max_length=30,
                    ),
                ),
                ("committee_date", models.DateField(blank=True, null=True)),
                ("action_plan", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mpdsr_cases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mpdsr_case",
                        to="submissions.kobosubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "MPDSR Case",
                "verbose_name_plural": "MPDSR Cases",
                "ordering": ["-date_of_death", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["partner", "status"],
                        name="mpdsr_mpdsr_partner_8246c1_idx",
                    ),
                    models.Index(
                        fields=["death_type", "partner"],
                        name="mpdsr_mpdsr_death_t_3bf239_idx",
                    ),
                ],
            },
        ),
    ]
