# Generated by Django 5.2.1 on 2026-05-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0002_mpdsr_place_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpdsrcase",
            name="sub_form_type",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="union",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="upazila",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mpdsrcase",
            name="cause_of_death",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="mpdsrcase",
            name="death_type",
            field=models.CharField(
                choices=[
                    ("maternal", "Maternal Death"),
                    ("perinatal", "Perinatal / Neonatal"),
                ],
                db_index=True,
                default="maternal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mpdsrcase",
            name="place_of_death",
            field=models.CharField(
                blank=True,
                choices=[
                    ("facility", "Health Facility"),
                    ("home", "Home"),
                    ("in_transit", "In Transit / On the Way"),
                ],
                default="facility",
                max_length=20,
            ),
        ),
    ]
