# Generated by Django 5.2.1 on 2026-06-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0003_mpdsrcase_sub_form_type_mpdsrcase_union_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MPDSRActionPlanSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(db_index=True, max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[("DM", "District"), ("UM", "Upazila")],
                        db_index=True,
                        max_length=4,
                    ),
                ),
                ("place_of_meeting", models.CharField(blank=True, max_length=200)),
                (
                    "meeting_date",
                    models.CharField(
                        blank=True,
                        help_text="Raw Excel date string — kept as text for messy formats",
                        max_length=40,
                    ),
                ),
                ("participants", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "meetings_planned",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of follow-up meetings planned"
                    ),
                ),
                ("activities_planned", models.PositiveIntegerField(default=0)),
                ("activities_implemented", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        db_index=True, default="excel_action_plan_2026", max_length=40
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MPDSR Action Plan Summary",
                "verbose_name_plural": "MPDSR Action Plan Summaries",
                "ordering": ["district", "level"],
            },
        ),
        migrations.CreateModel(
            name="MPDSRDistrictDenominator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "project_deaths_md",
                    models.FloatField(
                        blank=True,
                        help_text="Estimated maternal deaths 2026",
                        null=True,
                    ),
                ),
                (
                    "project_deaths_nd",
                    models.FloatField(
                        blank=True,
                        help_text="Estimated neonatal deaths 2026",
                        null=True,
                    ),
                ),
                (
                    "project_deaths_sb",
                    models.FloatField(
                        blank=True, help_text="Estimated stillbirths 2026", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True, default="excel_2026", max_length=40
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MPDSR District Denominator",
                "verbose_name_plural": "MPDSR District Denominators",
                "ordering": ["district"],
            },
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="source",
            field=models.CharField(db_index=True, default="kobo", max_length=40),
        ),
        migrations.CreateModel(
            name="MPDSRFacilityCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("facility_name", models.CharField(db_index=True, max_length=200)),
                (
                    "period",
                    models.CharField(
                        db_index=True,
                        default="2026",
                        help_text='Reporting period, e.g. "2026" or "2026-Q1"',
                        max_length=20,
                    ),
                ),
                ("fdn_md", models.PositiveIntegerField(default=0)),
                ("fdn_nd", models.PositiveIntegerField(default=0)),
                ("fdn_sb", models.PositiveIntegerField(default=0)),
                ("fdr_md", models.PositiveIntegerField(default=0)),
                ("fdr_nd", models.PositiveIntegerField(default=0)),
                ("fdr_sb", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        db_index=True, default="excel_2026", max_length=40
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MPDSR Facility Count",
                "verbose_name_plural": "MPDSR Facility Counts",
                "ordering": ["district", "facility_name"],
                "unique_together": {("district", "facility_name", "period")},
            },
        ),
    ]
