# Generated by Django 5.2.1 on 2026-06-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0005_mpdsrcase_logic_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpdsractionplansummary",
            name="actions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="mpdsrfacilitycount",
            name="cdn_md",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mpdsrfacilitycount",
            name="cdn_nd",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mpdsrfacilitycount",
            name="cdn_sb",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
