# Generated by Django 5.2.1 on 2026-06-07 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0006_mpdsractionplansummary_actions_and_more"),
        ("submissions", "0004_kobosubmission_is_zero_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaternalNearMissCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_serial",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "organisation",
                    models.CharField(db_index=True, default="CIPRB", max_length=20),
                ),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("upazila", models.CharField(blank=True, max_length=100)),
                ("union", models.CharField(blank=True, max_length=100)),
                ("village", models.CharField(blank=True, max_length=100)),
                ("woman_name", models.CharField(max_length=200)),
                ("woman_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "gestational_weeks",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("facility_name", models.CharField(blank=True, max_length=200)),
                ("event_date", models.DateField(db_index=True)),
                ("sev_pph", models.BooleanField(default=False)),
                ("sev_preec", models.BooleanField(default=False)),
                ("eclampsia", models.BooleanField(default=False)),
                ("sepsis", models.BooleanField(default=False)),
                ("rupt_uterus", models.BooleanField(default=False)),
                ("sev_abortion", models.BooleanField(default=False)),
                ("crit_blood", models.BooleanField(default=False)),
                ("crit_radiol", models.BooleanField(default=False)),
                ("crit_laparot", models.BooleanField(default=False)),
                ("crit_icu", models.BooleanField(default=False)),
                ("life_cardio", models.BooleanField(default=False)),
                ("life_resp", models.BooleanField(default=False)),
                ("life_renal", models.BooleanField(default=False)),
                ("life_coag", models.BooleanField(default=False)),
                ("life_hepatic", models.BooleanField(default=False)),
                ("life_neuro", models.BooleanField(default=False)),
                ("life_uterine", models.BooleanField(default=False)),
                ("mode_of_delivery", models.CharField(blank=True, max_length=30)),
                ("delivery_outcome", models.CharField(blank=True, max_length=20)),
                (
                    "cause_of_near_miss",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("contributory_conditions", models.TextField(blank=True)),
                ("audit_summary", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("enumerator_name", models.CharField(blank=True, max_length=200)),
                ("enumerator_mobile", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mnm_case",
                        to="submissions.kobosubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maternal Near Miss Case",
                "verbose_name_plural": "Maternal Near Miss Cases",
                "ordering": ["-event_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "event_date"],
                        name="mpdsr_mater_organis_c23cc6_idx",
                    ),
                    models.Index(
                        fields=["district", "event_date"],
                        name="mpdsr_mater_distric_a064e9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MPDSRDeathNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_serial",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "organisation",
                    models.CharField(db_index=True, default="CIPRB", max_length=20),
                ),
                (
                    "slip_variant",
                    models.CharField(
                        choices=[("01", "Slip 01"), ("02", "Slip 02")],
                        db_index=True,
                        default="01",
                        max_length=2,
                    ),
                ),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("upazila", models.CharField(blank=True, max_length=100)),
                ("union", models.CharField(blank=True, max_length=100)),
                ("village", models.CharField(blank=True, max_length=100)),
                (
                    "death_kind",
                    models.CharField(
                        choices=[
                            ("maternal", "Maternal death"),
                            ("neonatal", "Neonatal death"),
                            ("stillbirth", "Stillbirth"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("deceased_name", models.CharField(max_length=200)),
                (
                    "deceased_age",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("deceased_address", models.CharField(blank=True, max_length=300)),
                ("date_of_death", models.DateField(db_index=True)),
                (
                    "place_of_death",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("facility", "Health facility"),
                            ("in_transit", "In transit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cause_brief", models.CharField(blank=True, max_length=300)),
                ("reporter_name", models.CharField(max_length=200)),
                ("reporter_role", models.CharField(blank=True, max_length=20)),
                ("reporter_mobile", models.CharField(blank=True, max_length=30)),
                ("notification_date", models.DateField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mpdsr_notification",
                        to="submissions.kobosubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "MPDSR Death Notification",
                "verbose_name_plural": "MPDSR Death Notifications",
                "ordering": ["-date_of_death", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "death_kind"],
                        name="mpdsr_mpdsr_organis_4729b3_idx",
                    ),
                    models.Index(
                        fields=["district", "date_of_death"],
                        name="mpdsr_mpdsr_distric_0688b0_idx",
                    ),
                ],
            },
        ),
    ]
