# Generated by Django 5.2.1 on 2026-06-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0007_maternalnearmisscase_mpdsrdeathnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpdsrcase",
            name="anc_visits_count",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="delivery_outcome",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="gestational_weeks",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="mode_of_delivery",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="person_assisted_delivery",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="place_of_delivery",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="pnc_received",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="time_death_after_birth_hours",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="time_of_death",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
