# Generated by Django 5.2.1 on 2026-06-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0008_mpdsrcase_anc_visits_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpdsrcase",
            name="admission_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
