# Generated by Django 5.2.1 on 2026-06-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0009_mpdsrcase_admission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="crit_blood",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="crit_icu",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="crit_laparot",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="crit_radiol",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="eclampsia",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="life_cardio",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="life_coag",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="life_hepatic",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="life_neuro",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="life_renal",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="life_resp",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="life_uterine",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="rupt_uterus",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="sepsis",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="sev_abortion",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="sev_pph",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="sev_preec",
            field=models.BooleanField(null=True),
        ),
    ]
