# Generated by Django 5.2.1 on 2026-06-20 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0010_alter_maternalnearmisscase_crit_blood_and_more"),
        ("programs", "0018_alter_client_education_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maternalnearmisscase",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="APPROVED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="maternalnearmisscase",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maternalnearmisscase",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maternalnearmisscase",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="programs.servicecenter",
            ),
        ),
        migrations.AddField(
            model_name="maternalnearmisscase",
            name="kobo_submission_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="maternalnearmisscase",
            name="rejected_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="maternalnearmisscase",
            name="submitted_by_kobo_user",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="APPROVED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="programs.servicecenter",
            ),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="kobo_submission_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="organisation",
            field=models.CharField(db_index=True, default="CIPRB", max_length=20),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="rejected_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="submitted_by_kobo_user",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="mpdsrdeathnotification",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="APPROVED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mpdsrdeathnotification",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mpdsrdeathnotification",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mpdsrdeathnotification",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="programs.servicecenter",
            ),
        ),
        migrations.AddField(
            model_name="mpdsrdeathnotification",
            name="kobo_submission_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="mpdsrdeathnotification",
            name="rejected_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mpdsrdeathnotification",
            name="submitted_by_kobo_user",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
