# Generated by Django 5.2.1 on 2026-06-23 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0011_maternalnearmisscase_approval_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MPDSRAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_id",
                    models.CharField(
                        db_index=True,
                        help_text="'<district-code>-<NN>', e.g. D-01.",
                        max_length=12,
                    ),
                ),
                ("district", models.CharField(db_index=True, max_length=100)),
                (
                    "organisation",
                    models.CharField(db_index=True, default="CIPRB", max_length=20),
                ),
                (
                    "meeting_date",
                    models.DateField(
                        blank=True,
                        help_text="Review meeting where the action was agreed.",
                        null=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("system_strengthening", "MPDSR System Strengthening"),
                            (
                                "community_va",
                                "Common modifiable factors (Community VA)",
                            ),
                            ("facility_dr", "Common modifiable factors (Facility DR)"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        blank=True,
                        help_text="System-Strengthening sub-category (Community Death Review, …).",
                        max_length=120,
                    ),
                ),
                (
                    "activity",
                    models.TextField(help_text="The action / activity to be taken."),
                ),
                ("responsible", models.CharField(blank=True, max_length=200)),
                (
                    "timeline",
                    models.DateField(blank=True, help_text="Target date.", null=True),
                ),
                ("indicator", models.TextField(blank=True)),
                ("milestone", models.TextField(blank=True)),
                ("considerations", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending / not started"),
                            ("in_progress", "In progress"),
                            ("implemented", "Implemented"),
                            ("delayed", "Delayed"),
                            ("dropped", "Dropped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "completion_pct",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "0%"),
                            (25, "25%"),
                            (50, "50%"),
                            (75, "75%"),
                            (100, "100%"),
                        ],
                        default=0,
                    ),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Latest progress note."),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="APPROVED",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True, default="")),
                (
                    "kobo_submission_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "source",
                    models.CharField(db_index=True, default="kobo", max_length=40),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audit_trail", models.JSONField(blank=True, default=list)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MPDSR Action",
                "verbose_name_plural": "MPDSR Actions",
                "ordering": ["district", "action_id"],
                "indexes": [
                    models.Index(
                        fields=["district", "status"],
                        name="mpdsr_mpdsr_distric_7c02c9_idx",
                    ),
                    models.Index(
                        fields=["section", "status"],
                        name="mpdsr_mpdsr_section_95a416_idx",
                    ),
                    models.Index(
                        fields=["timeline", "status"],
                        name="mpdsr_mpdsr_timelin_cc883f_idx",
                    ),
                ],
                "unique_together": {("district", "action_id")},
            },
        ),
    ]
