# Generated by Django 5.2.1 on 2026-06-25 09:11

import fistula.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0012_mpdsraction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="enumerator_mobile",
            field=fistula.encryption.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="enumerator_name",
            field=fistula.encryption.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="woman_name",
            field=fistula.encryption.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="mpdsrdeathnotification",
            name="deceased_address",
            field=fistula.encryption.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="mpdsrdeathnotification",
            name="deceased_name",
            field=fistula.encryption.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="mpdsrdeathnotification",
            name="reporter_mobile",
            field=fistula.encryption.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="mpdsrdeathnotification",
            name="reporter_name",
            field=fistula.encryption.EncryptedCharField(),
        ),
    ]
