# Generated by Django 5.2.1 on 2026-06-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0013_alter_maternalnearmisscase_enumerator_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maternalnearmisscase",
            name="woman_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="mpdsrdeathnotification",
            name="deceased_name",
            field=models.CharField(max_length=200),
        ),
    ]
