# Generated by Django 5.2.1 on 2026-06-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0014_alter_maternalnearmisscase_woman_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpdsraction",
            name="creator_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="mpdsraction",
            name="last_edited_by_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
