# Generated by Django 5.2.1 on 2026-06-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0015_mpdsraction_creator_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpdsraction",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
