# Generated by Django 5.2.1 on 2026-06-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0016_alter_mpdsraction_approval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpdsrcase",
            name="raw_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
