# Generated by Django 5.2.1 on 2026-07-26 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0018_dedupe_blank_serial_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="CIPRBReconSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("run_at", models.DateTimeField(db_index=True)),
                ("data", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "CIPRB reconciliation snapshot",
                "ordering": ["-run_at"],
            },
        ),
    ]
