# Generated by Django 5.2.1 on 2026-07-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0019_ciprbreconsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpdsrcase",
            name="sa_death_kind",
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
    ]
