# Generated by Django 5.2.1 on 2026-08-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpdsr", "0021_backfill_sa_death_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="maternalnearmisscase",
            name="system_ref",
            field=models.CharField(
                blank=True, db_index=True, max_length=24, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="mpdsrcase",
            name="system_ref",
            field=models.CharField(
                blank=True, db_index=True, max_length=24, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="mpdsrdeathnotification",
            name="system_ref",
            field=models.CharField(
                blank=True, db_index=True, max_length=24, null=True, unique=True
            ),
        ),
    ]
