# Generated by Django 5.2.1 on 2026-05-26 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partners", "0001_initial"),
        ("programs", "0005_alter_coordmeeting_photo_alter_trainingevent_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.CharField(db_index=True, max_length=64)),
                ("date", models.DateField(db_index=True)),
                (
                    "drug",
                    models.CharField(
                        choices=[
                            ("metronidazole", "Metronidazole"),
                            ("doxycycline", "Doxycycline"),
                            ("b_complex", "B-Complex"),
                            ("ibuprofen", "Ibuprofen"),
                            ("paracetamol", "Paracetamol"),
                            ("ranitidine", "Ranitidine"),
                            ("antacid", "Antacid"),
                            ("ors", "ORS (Oral Rehydration Salts)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField()),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("STI", "STI"),
                            ("GENERAL", "General"),
                            ("SEVERE", "Severe (ORS only)"),
                        ],
                        default="GENERAL",
                        max_length=10,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="programs.servicecenter",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="partners.partner",
                    ),
                ),
                (
                    "prescribed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["drug", "date"], name="pharmacy_pr_drug_603a52_idx"
                    ),
                    models.Index(
                        fields=["partner", "date"],
                        name="pharmacy_pr_partner_15d8f8_idx",
                    ),
                ],
            },
        ),
    ]
