# Generated by Django 5.2.1 on 2026-05-23 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FistulaCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, unique=True
                    ),
                ),
                ("partner", models.CharField(db_index=True, max_length=20)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("date_identified", models.DateField()),
                ("patient_name_enc", models.TextField(blank=True)),
                ("patient_id_enc", models.TextField(blank=True)),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Case Identified"),
                            ("action_required", "Action Required"),
                            ("followup_pending", "Follow-up Pending"),
                            ("referral_completed", "Referral Completed"),
                        ],
                        db_index=True,
                        default="identified",
                        max_length=30,
                    ),
                ),
                ("referral_status", models.CharField(blank=True, max_length=200)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fistula_cases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fistula_case",
                        to="submissions.kobosubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_identified", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["partner", "status"],
                        name="fistula_fis_partner_09eea3_idx",
                    ),
                    models.Index(
                        fields=["follow_up_date", "status"],
                        name="fistula_fis_follow__54286b_idx",
                    ),
                ],
            },
        ),
    ]
