# Generated by Django 5.2.1 on 2026-05-24 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0001_initial"),
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FistulaCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, unique=True
                    ),
                ),
                ("partner", models.CharField(db_index=True, max_length=20)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("upazila", models.CharField(blank=True, max_length=100)),
                ("union", models.CharField(blank=True, max_length=100)),
                ("village", models.CharField(blank=True, max_length=200)),
                ("facility_name", models.CharField(blank=True, max_length=200)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("campaign_date", models.DateField()),
                ("women_screened", models.PositiveIntegerField(default=0)),
                ("women_reached_awareness", models.PositiveIntegerField(default=0)),
                ("men_reached_awareness", models.PositiveIntegerField(default=0)),
                ("community_sessions", models.PositiveSmallIntegerField(default=0)),
                (
                    "suspected_fistula_cases",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "confirmed_fistula_cases",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("new_cases", models.PositiveSmallIntegerField(default=0)),
                ("repeat_cases", models.PositiveSmallIntegerField(default=0)),
                ("fistula_type", models.CharField(blank=True, max_length=300)),
                ("fistula_cause", models.CharField(blank=True, max_length=300)),
                ("cases_referred", models.PositiveSmallIntegerField(default=0)),
                (
                    "cases_accepted_referral",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("cases_reached_facility", models.PositiveSmallIntegerField(default=0)),
                (
                    "cases_surgery_completed",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("cases_surgery_pending", models.PositiveSmallIntegerField(default=0)),
                (
                    "cases_surgery_not_eligible",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("cases_followup_due", models.PositiveSmallIntegerField(default=0)),
                (
                    "cases_followup_completed",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("cases_lost_followup", models.PositiveSmallIntegerField(default=0)),
                (
                    "cases_counselling_provided",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "cases_social_reintegration",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("main_barriers", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fistula_campaigns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fistula_campaign",
                        to="submissions.kobosubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fistula Campaign Session",
                "verbose_name_plural": "Fistula Campaign Sessions",
                "ordering": ["-campaign_date", "-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="FistulaCase",
        ),
        migrations.AddIndex(
            model_name="fistulacampaign",
            index=models.Index(
                fields=["partner", "campaign_date"],
                name="fistula_fis_partner_319b5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fistulacampaign",
            index=models.Index(
                fields=["district", "campaign_date"],
                name="fistula_fis_distric_7928c5_idx",
            ),
        ),
    ]
