# Generated by Django 5.2.1 on 2026-05-27 21:33

import django.db.models.deletion
import fistula.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0002_fistulacampaign_delete_fistulacase_and_more"),
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FistulaCampaignVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, unique=True
                    ),
                ),
                ("visit_date", models.DateField(db_index=True)),
                ("patient_name", fistula.models.EncryptedCharField(blank=True)),
                ("husband_name", fistula.models.EncryptedCharField(blank=True)),
                ("contact_number", fistula.models.EncryptedCharField(blank=True)),
                ("age_years", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("education", models.CharField(blank=True, max_length=100)),
                ("profession", models.CharField(blank=True, max_length=200)),
                ("husband_profession", models.CharField(blank=True, max_length=200)),
                ("village", models.CharField(blank=True, max_length=200)),
                ("union", models.CharField(blank=True, max_length=100)),
                ("upazila", models.CharField(blank=True, max_length=100)),
                (
                    "district",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "from_haor",
                    models.BooleanField(
                        blank=True,
                        help_text="Patient lives in a Haor (wetland) area.",
                        null=True,
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("facility", "Facility"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delivery_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LB", "Live Birth"),
                            ("SB", "Still Birth"),
                            ("UNK", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "suffering_duration",
                    models.CharField(
                        blank=True,
                        help_text='Free-text — e.g. "30 years", "8 years".',
                        max_length=100,
                    ),
                ),
                (
                    "info_source",
                    models.CharField(
                        blank=True,
                        help_text="Who reported the suspected case — DRC / FWA / Midwife / Self.",
                        max_length=100,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fistula_campaign_visit",
                        to="submissions.kobosubmission",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fistula Campaign Visit",
                "verbose_name_plural": "Fistula Campaign Visits",
                "ordering": ["-visit_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["district", "-visit_date"],
                        name="fistula_fis_distric_d33f80_idx",
                    ),
                    models.Index(
                        fields=["union", "-visit_date"],
                        name="fistula_fis_union_dd3d28_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FistulaCornerCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, unique=True
                    ),
                ),
                ("patient_name", fistula.models.EncryptedCharField(blank=True)),
                ("husband_name", fistula.models.EncryptedCharField(blank=True)),
                ("mobile_number", fistula.models.EncryptedCharField(blank=True)),
                ("age_years", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("village", models.CharField(blank=True, max_length=200)),
                ("union", models.CharField(blank=True, max_length=100)),
                ("upazila", models.CharField(blank=True, max_length=100)),
                (
                    "district",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("suspected_date", models.DateField(blank=True, null=True)),
                ("identification_date", models.DateField(blank=True, null=True)),
                (
                    "diagnosis_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("informant_name", models.CharField(blank=True, max_length=200)),
                ("informant_designation", models.CharField(blank=True, max_length=200)),
                (
                    "suffering_duration",
                    models.CharField(
                        blank=True,
                        help_text='Free-text duration — e.g. "৩ বছর", "8 মাস".',
                        max_length=100,
                    ),
                ),
                (
                    "fistula_cause",
                    models.CharField(
                        blank=True,
                        help_text='Free-text — e.g. "দীর্ঘ সময়ের প্রসব" (prolonged labour).',
                        max_length=300,
                    ),
                ),
                (
                    "fistula_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VVF", "V.V.F (Vesico-Vaginal Fistula)"),
                            ("RVF", "R.V.F (Recto-Vaginal Fistula)"),
                            ("BOTH", "V.V.F + R.V.F (Combined)"),
                            ("OTHER", "Other"),
                        ],
                        help_text="V.V.F / R.V.F / Combined / Other.",
                        max_length=10,
                    ),
                ),
                ("service_provider_name", models.CharField(blank=True, max_length=200)),
                (
                    "service_provider_designation",
                    models.CharField(blank=True, max_length=200),
                ),
                ("referral_date", models.DateField(blank=True, null=True)),
                ("referral_place", models.CharField(blank=True, max_length=200)),
                (
                    "surgery_performed",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No"), ("pending", "Pending")],
                        max_length=10,
                    ),
                ),
                ("referral_outcome", models.TextField(blank=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fistula_corner_case",
                        to="submissions.kobosubmission",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fistula Corner Case",
                "verbose_name_plural": "Fistula Corner Cases",
                "ordering": ["-diagnosis_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["district", "-diagnosis_date"],
                        name="fistula_fis_distric_433f80_idx",
                    ),
                    models.Index(
                        fields=["fistula_type"], name="fistula_fis_fistula_4a0f23_idx"
                    ),
                ],
            },
        ),
    ]
