# Generated by Django 5.2.1 on 2026-06-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0003_corner_and_campaign_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="fistulacornercase",
            name="source",
            field=models.CharField(db_index=True, default="kobo", max_length=40),
        ),
    ]
