# Generated by Django 5.2.1 on 2026-06-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0004_fistulacornercase_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="fistulacampaign",
            name="households_visited",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="population_covered",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
