# Generated by Django 5.2.1 on 2026-06-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0005_fistulacampaign_households_visited_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fistulacornercase",
            name="received_rehab_support",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="fistulacornercase",
            name="rehab_support_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fistulacornercase",
            name="rehab_support_types",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated: Cash, Livestock, Training, Tree plant, Sewing machine, VGF Card, Disability card, Psychosocial support, Reintegration support",
                max_length=300,
            ),
        ),
    ]
