# Generated by Django 5.2.1 on 2026-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0006_fistulacornercase_received_rehab_support_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fistulacornercase",
            name="patient_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
