# Generated by Django 5.2.1 on 2026-06-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0007_fistulacornercase_patient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fistulacornercase",
            name="surgery_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success_dry", "Successfully repaired and dry"),
                    ("success_not_dry", "Successfully repaired but not dry"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                help_text="Clinical outcome for repaired cases: dry / not-dry / failed.",
                max_length=20,
            ),
        ),
    ]
