# Generated by Django 5.2.1 on 2026-06-07 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0008_fistulacornercase_surgery_outcome"),
        ("submissions", "0004_kobosubmission_is_zero_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="CIPRBFistulaCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_serial",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="CIPRB annual fistula serial (from the paper form).",
                        max_length=50,
                    ),
                ),
                (
                    "organisation",
                    models.CharField(db_index=True, default="CIPRB", max_length=20),
                ),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("upazila", models.CharField(blank=True, max_length=100)),
                ("union", models.CharField(blank=True, max_length=100)),
                ("village", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("education", models.CharField(blank=True, max_length=30)),
                ("husband", models.CharField(blank=True, max_length=200)),
                ("husband_profession", models.CharField(blank=True, max_length=200)),
                ("profession_patient", models.CharField(blank=True, max_length=200)),
                ("current_condition", models.CharField(blank=True, max_length=200)),
                ("contact_number", models.CharField(blank=True, max_length=30)),
                ("marital_status", models.CharField(blank=True, max_length=20)),
                (
                    "age_at_marriage",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "age_at_first_delivery",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "number_of_children",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("delivery_complication", models.CharField(blank=True, max_length=200)),
                (
                    "last_delivery_labour_duration",
                    models.CharField(blank=True, max_length=100),
                ),
                ("mode_of_last_delivery", models.CharField(blank=True, max_length=30)),
                ("place_of_last_delivery", models.CharField(blank=True, max_length=30)),
                (
                    "conducted_last_delivery",
                    models.CharField(blank=True, max_length=30),
                ),
                ("delivery_outcome", models.CharField(blank=True, max_length=20)),
                (
                    "reasons_no_institutional_delivery",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "time_duration_fistula_occurrence",
                    models.CharField(blank=True, max_length=100),
                ),
                ("duration_suffering", models.CharField(blank=True, max_length=100)),
                ("suspected_date", models.DateField(blank=True, null=True)),
                ("source_information", models.CharField(blank=True, max_length=200)),
                ("diagnosed_date", models.DateField(blank=True, null=True)),
                ("diagnosed_place", models.CharField(blank=True, max_length=200)),
                ("diagnosed_by", models.CharField(blank=True, max_length=200)),
                ("refer_date", models.DateField(blank=True, null=True)),
                ("refer_place", models.CharField(blank=True, max_length=200)),
                ("referred_by_person", models.CharField(blank=True, max_length=200)),
                ("refer_outcome", models.CharField(blank=True, max_length=30)),
                ("operation_date", models.DateField(blank=True, null=True)),
                ("operation_place", models.CharField(blank=True, max_length=200)),
                (
                    "hospital_stay_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "times_of_operations",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "fistula_type_v2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("obstetric", "Obstetric"),
                            ("iatrogenic", "Iatrogenic"),
                            ("congenital", "Congenital"),
                            ("traumatic", "Traumatic"),
                        ],
                        db_index=True,
                        help_text="4-category fistula type per CIPRB Question Bank.",
                        max_length=20,
                    ),
                ),
                ("iatrogenic_cause", models.CharField(blank=True, max_length=30)),
                ("genital_fistula_type", models.CharField(blank=True, max_length=30)),
                ("operation_route", models.CharField(blank=True, max_length=30)),
                (
                    "surgery_outcome_v2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success_dry", "Successfully repaired with a dry vagina"),
                            ("success_not_dry", "Successfully repaired but not dry"),
                            ("failed", "Failed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rehabilitation_received", models.BooleanField(null=True)),
                ("rehabilitation_date", models.DateField(blank=True, null=True)),
                ("rehab_place", models.CharField(blank=True, max_length=50)),
                ("rehab_support_types", models.CharField(blank=True, max_length=500)),
                ("rehab_notes", models.TextField(blank=True)),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("suspected", "Suspected"),
                            ("diagnosed", "Diagnosed"),
                            ("referred", "Referred for Surgical Management"),
                            ("repaired", "Surgically Repaired"),
                            ("rehabilitated", "Rehabilitated & Reintegrated"),
                        ],
                        db_index=True,
                        default="suspected",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("enumerator_name", models.CharField(blank=True, max_length=200)),
                ("enumerator_mobile", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ciprb_fistula_case",
                        to="submissions.kobosubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "CIPRB Fistula Case",
                "verbose_name_plural": "CIPRB Fistula Cases",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "current_stage"],
                        name="fistula_cip_organis_467e23_idx",
                    ),
                    models.Index(
                        fields=["district", "current_stage"],
                        name="fistula_cip_distric_445187_idx",
                    ),
                    models.Index(
                        fields=["district", "case_serial"],
                        name="fistula_cip_distric_17ee4e_idx",
                    ),
                ],
            },
        ),
    ]
