# Generated by Django 5.2.1 on 2026-06-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0009_ciprbfistulacase"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciprbfistulacase",
            name="patient_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique fistula patient ID: <district-code>-<4-digit serial>.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
