# Generated by Django 5.2.1 on 2026-06-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0011_ciprbfistulacase_approval_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciprbfistulacase",
            name="genital_fistula_type",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
