# Generated by Django 5.2.1 on 2026-06-25 09:11

import fistula.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0012_alter_ciprbfistulacase_genital_fistula_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciprbfistulacase",
            name="contact_number",
            field=fistula.encryption.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="ciprbfistulacase",
            name="husband",
            field=fistula.encryption.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="ciprbfistulacase",
            name="name",
            field=fistula.encryption.EncryptedCharField(),
        ),
    ]
