# Generated by Django 5.2.1 on 2026-06-25 09:29

import fistula.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0013_alter_ciprbfistulacase_contact_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fistulacornercase",
            name="informant_name",
            field=fistula.models.EncryptedCharField(blank=True),
        ),
    ]
