# Generated by Django 5.2.1 on 2026-07-01 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0014_alter_fistulacornercase_informant_name"),
        ("programs", "0020_wellnesslogbookentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fistulacampaign",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="programs.servicecenter",
            ),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="enumerator_mobile",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="enumerator_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="focal_cc",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="focal_community",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="focal_epi",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="focal_fwc",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="kobo_submission_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="organisation",
            field=models.CharField(db_index=True, default="CIPRB", max_length=20),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="raw_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="rejected_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="staff_chcp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="staff_chw",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="staff_fpi",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="staff_fwa",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="staff_fwv",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="staff_ha",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="staff_hi_ahi",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fistulacampaign",
            name="submitted_by_kobo_user",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
