# Generated by Django 5.2.1 on 2026-09-09 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fistula", "0015_fistulacampaign_approval_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CIPRBFistulaCaseCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cost_point",
                    models.CharField(
                        choices=[
                            (
                                "referred",
                                "Referral (travel, investigation, no surgery yet)",
                            ),
                            ("repaired", "Surgical repair"),
                        ],
                        db_index=True,
                        default="repaired",
                        help_text="Which point in the pathway this money was spent at.",
                        max_length=20,
                    ),
                ),
                (
                    "episode_no",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Which occurrence (1st operation, 2nd operation…).",
                    ),
                ),
                ("cost_date", models.DateField(blank=True, null=True)),
                (
                    "amount_disbursed",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Amount released to the patient for this episode.",
                        null=True,
                    ),
                ),
                (
                    "disbursed_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="District Coordinator who handed the money over.",
                        max_length=200,
                    ),
                ),
                ("medical_cost", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "investigation_cost",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("ot_cost", models.PositiveIntegerField(blank=True, null=True)),
                ("travel_cost", models.PositiveIntegerField(blank=True, null=True)),
                ("food_cost", models.PositiveIntegerField(blank=True, null=True)),
                ("other_cost", models.PositiveIntegerField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "kobo_submission_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="fistula.ciprbfistulacase",
                    ),
                ),
            ],
            options={
                "verbose_name": "CIPRB Fistula Case Cost",
                "verbose_name_plural": "CIPRB Fistula Case Costs",
                "ordering": ["case", "cost_point", "episode_no"],
                "indexes": [
                    models.Index(
                        fields=["cost_point", "cost_date"],
                        name="fistula_cip_cost_po_260fcf_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("case", "cost_point", "episode_no"),
                        name="uniq_fistula_cost_per_episode",
                    )
                ],
            },
        ),
    ]
