# Generated by Django 5.2.1 on 2026-05-23 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineSurvey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("partner", models.CharField(db_index=True, max_length=20)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "survey_type",
                    models.CharField(
                        choices=[("baseline", "Baseline"), ("endline", "Endline")],
                        db_index=True,
                        default="baseline",
                        max_length=20,
                    ),
                ),
                (
                    "participant_code",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("date_conducted", models.DateField()),
                ("raw_data", models.JSONField(default=dict)),
                ("is_duplicate", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="baseline.baselinesurvey",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_survey",
                        to="submissions.kobosubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_conducted", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["partner", "survey_type"],
                        name="baseline_ba_partner_1e3d3b_idx",
                    ),
                    models.Index(
                        fields=["participant_code", "district", "survey_type"],
                        name="baseline_ba_partici_519e93_idx",
                    ),
                ],
            },
        ),
    ]
