# Generated by Django 5.2.1 on 2026-05-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baselinesurvey",
            options={"ordering": ["-survey_date", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="baselinesurvey",
            name="date_conducted",
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="anc_4visits",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="child_marriage_knowledge",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="currently_pregnant",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="danger_signs_knowledge",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="education",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="facility_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="fistula_awareness",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="fp_method",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="fp_use",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="gbv_awareness",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="health_facility_distance",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="mpdsr_awareness",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="respondent_age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="ses",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="sex",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="skilled_birth_attendant",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="srh_service_satisfaction",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="survey_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="union",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="baselinesurvey",
            name="upazila",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
