# Generated by Django 5.2.1 on 2026-06-25 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0002_alter_baselinesurvey_options_and_more"),
        ("submissions", "0004_kobosubmission_is_zero_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "population",
                    models.CharField(
                        choices=[
                            ("hijra", "Hijra / Gender-diverse"),
                            ("fsw", "Female Sex Worker"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "survey_round",
                    models.CharField(
                        choices=[("baseline", "Baseline"), ("endline", "Endline")],
                        db_index=True,
                        default="baseline",
                        max_length=20,
                    ),
                ),
                (
                    "partner",
                    models.CharField(db_index=True, default="CIPRB", max_length=20),
                ),
                (
                    "district",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("site_code", models.CharField(blank=True, max_length=80)),
                ("serial", models.CharField(blank=True, db_index=True, max_length=100)),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("interview_outcome", models.CharField(blank=True, max_length=120)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("is_duplicate", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="baseline.baselineresponse",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_response",
                        to="submissions.kobosubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["population", "survey_round"],
                        name="baseline_ba_populat_391efa_idx",
                    ),
                    models.Index(
                        fields=["population", "district"],
                        name="baseline_ba_populat_eadb54_idx",
                    ),
                    models.Index(
                        fields=["serial", "population", "survey_round"],
                        name="baseline_ba_serial_9dde46_idx",
                    ),
                ],
            },
        ),
    ]
