# Generated by Django 5.2.1 on 2026-07-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0004_anomalyreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anomalyreview",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("confirmed", "Confirmed"),
                    ("corrected", "Corrected"),
                    ("false_positive", "False positive"),
                    ("needs_verification", "Needs field verification"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
