# Generated by Django 5.2.1 on 2026-05-24 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndicatorTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("indicator_code", models.CharField(db_index=True, max_length=30)),
                ("indicator_name", models.CharField(max_length=300)),
                ("objective", models.CharField(blank=True, max_length=10)),
                ("activity_ref", models.CharField(blank=True, max_length=20)),
                ("unit", models.CharField(default="count", max_length=50)),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Indicator Target",
                "verbose_name_plural": "Indicator Targets",
                "ordering": ["organisation", "indicator_code"],
                "unique_together": {("organisation", "indicator_code", "period_start")},
            },
        ),
    ]
