# Generated by Django 5.2.1 on 2026-05-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatortarget",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
