# Generated by Django 5.2.1 on 2026-05-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0004_load_target_fixtures"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatortarget",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="indicator_targets",
                to="partners.partner",
            ),
        ),
        migrations.AlterField(
            model_name="indicatortarget",
            name="unit",
            field=models.CharField(
                default="count",
                help_text="e.g. 'individuals', 'sessions', 'boxes', 'pcs', 'meetings'.",
                max_length=50,
            ),
        ),
    ]
