# Generated by Django 5.2.1 on 2026-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0007_wire_ciprb_fistula_baseline"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatortarget",
            name="monthly_targets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Partner-defined monthly splits — list of {month, target}.",
            ),
        ),
    ]
