# Generated by Django 5.2.1 on 2026-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remap_super_admin_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("developer", "Developer"),
                    ("supervisor", "UNFPA / Supervisor"),
                    ("org_lead", "Org Lead"),
                    ("manager", "Wellness Center Manager"),
                    ("field_staff", "Field Staff / Lab Technician"),
                    ("ciprb_baseline", "CIPRB Baseline Entry"),
                    ("focal", "Focal Person (view-only)"),
                ],
                default="manager",
                max_length=20,
            ),
        ),
    ]
