# Generated by Django 5.2.1 on 2026-05-23 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KoboSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kobo_id", models.CharField(max_length=100, unique=True)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("mpdsr", "MPDSR"),
                            ("fistula", "Fistula Campaign"),
                            ("activity", "Activity Report"),
                            ("baseline", "Baseline/Endline Survey"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("partner", models.CharField(blank=True, db_index=True, max_length=20)),
                ("worker_name", models.CharField(blank=True, max_length=200)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("raw_data", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["partner", "status", "-submitted_at"],
                        name="submissions_partner_36d8a7_idx",
                    ),
                    models.Index(
                        fields=["form_type", "status"],
                        name="submissions_form_ty_71b19a_idx",
                    ),
                ],
            },
        ),
    ]
