# Generated by Django 5.2.1 on 2026-06-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kobosubmission",
            name="centre_code",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
