# Generated by Django 5.2.1 on 2026-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_kobosubmission_centre_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="kobosubmission",
            name="review_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="kobosubmission",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("mpdsr", "MPDSR"),
                    ("fistula", "Fistula Campaign"),
                    ("activity", "Activity Report"),
                    ("baseline", "Baseline/Endline Survey"),
                    ("fistula_staged", "Fistula Staged (Auto-ID, 5 stages)"),
                    ("mpdsr_response_plan", "MPDSR Response Plan"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
