# Generated by Django 5.2.1 on 2026-06-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_kobosubmission_review_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kobosubmission",
            name="is_zero_report",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
