# Generated by Django 5.2.1 on 2026-05-23 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("monthly_summary", "Monthly Summary"),
                            ("one_pager", "One-Pager"),
                            ("newsletter", "Newsletter"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("pptx", "PowerPoint"),
                        ],
                        max_length=10,
                    ),
                ),
                ("partner", models.CharField(blank=True, db_index=True, max_length=20)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=300)),
                ("narrative", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="reports/%Y/%m/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["partner", "year", "month"],
                        name="reports_rep_partner_d2b6d3_idx",
                    )
                ],
            },
        ),
    ]
