# Generated by Django 5.2.1 on 2026-05-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="period_type",
            field=models.CharField(
                choices=[
                    ("biweekly", "Bi-Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                ],
                db_index=True,
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="month",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("monthly_summary", "Monthly Summary"),
                    ("one_pager", "Infographic"),
                    ("newsletter", "Newsletter"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="year",
            field=models.PositiveSmallIntegerField(default=2026),
        ),
    ]
