# Generated by Django 5.2.1 on 2026-05-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_add_period_type_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="model_used",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="report",
            name="narrative_source",
            field=models.CharField(
                choices=[
                    ("ai", "AI (validated)"),
                    ("ai_validation_failed", "AI (validation failed → fallback)"),
                    ("ai_disabled", "AI disabled by user"),
                    ("insufficient_data", "Insufficient data — template used"),
                    ("ai_api_error", "AI API error → fallback"),
                    ("template", "Template only"),
                    ("hand_written_demo", "Hand-written demo content"),
                ],
                db_index=True,
                default="template",
                max_length=30,
            ),
        ),
    ]
