# Generated by Django 5.2.1 on 2026-06-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_report_model_used_report_narrative_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="file_bytes",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="original_filename",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
