# Generated by Django 5.2.1 on 2026-06-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_report_file_bytes_report_original_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="share_token",
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name="report",
            name="format",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("docx", "Word Document"),
                    ("pptx", "PowerPoint"),
                    ("png", "Image (PNG)"),
                    ("html", "Web Page"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("monthly_summary", "Monthly Summary"),
                    ("one_pager", "Infographic"),
                    ("newsletter", "Newsletter"),
                    ("web_report", "Web Report"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
