# Generated by Django 5.2.1 on 2026-05-24 17:47

import django.db.models.deletion
import programs.models.gbv
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "client_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("mother_name", models.CharField(blank=True, max_length=200)),
                ("father_name", models.CharField(blank=True, max_length=200)),
                ("birth_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "Male"),
                            ("02", "Female"),
                            ("03", "Transgender"),
                            ("04", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "target_group_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "MSM"),
                            ("02", "MSW / Kothi"),
                            ("03", "Transgender"),
                            ("04", "Others"),
                            ("05", "FSW"),
                            ("06", "PWID"),
                        ],
                        max_length=2,
                    ),
                ),
                ("current_address", models.TextField(blank=True)),
                ("spot_name", models.CharField(blank=True, max_length=200)),
                ("marital_status", models.CharField(blank=True, max_length=1)),
                ("education_level", models.CharField(blank=True, max_length=1)),
                ("occupation_code", models.CharField(blank=True, max_length=1)),
                (
                    "years_in_profession",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "avg_clients_per_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "children_under_18",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("uses_injecting_drugs", models.BooleanField(null=True)),
                ("has_nid", models.BooleanField(null=True)),
                ("uses_fp_method", models.BooleanField(null=True)),
                ("enrolled_date", models.DateField(blank=True, null=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("1", "Active"),
                            ("2", "Jailed"),
                            ("3", "Relocated"),
                            ("4", "Other"),
                            ("5", "Deceased"),
                            ("6", "Not Found"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                ("telegram_chat_id", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-enrolled_date"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCenter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_bangla", models.CharField(blank=True, max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "center_type",
                    models.CharField(
                        choices=[
                            ("DIC", "Drop-In Center"),
                            ("BROTHEL", "Brothel-Based Center"),
                            ("SUB_DIC", "Sub Drop-In Center"),
                            ("MOBILE", "Mobile Outreach"),
                        ],
                        max_length=20,
                    ),
                ),
                ("district", models.CharField(max_length=100)),
                ("upazila", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["organisation", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClinicVisit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("visit_date", models.DateField(db_index=True)),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("follow_up", "Follow-Up"),
                            ("recurrent", "Recurrent"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("monthly_serial", models.CharField(blank=True, max_length=20)),
                ("sti_screening_done", models.BooleanField(default=False)),
                ("hiv_screening_done", models.BooleanField(default=False)),
                ("tb_screening_done", models.BooleanField(default=False)),
                ("diabetic_screening_done", models.BooleanField(default=False)),
                ("hep_b_screening_done", models.BooleanField(default=False)),
                ("hep_c_screening_done", models.BooleanField(default=False)),
                ("diag_uds", models.BooleanField(default=False)),
                ("diag_vds", models.BooleanField(default=False)),
                ("diag_gu", models.BooleanField(default=False)),
                ("diag_pid", models.BooleanField(default=False)),
                ("diag_ss", models.BooleanField(default=False)),
                ("diag_ib", models.BooleanField(default=False)),
                ("diag_anal_sti", models.BooleanField(default=False)),
                ("diag_other", models.BooleanField(default=False)),
                ("diag_other_specify", models.CharField(blank=True, max_length=200)),
                ("diag_gh", models.BooleanField(default=False)),
                ("diag_psd", models.BooleanField(default=False)),
                ("diag_mental_health", models.BooleanField(default=False)),
                ("treatment_provided", models.TextField(blank=True)),
                (
                    "seeking_treatment_timing",
                    models.CharField(blank=True, max_length=20),
                ),
                ("condom_demo_sessions", models.PositiveSmallIntegerField(default=0)),
                ("condoms_distributed", models.PositiveIntegerField(default=0)),
                ("sti_counselling_provided", models.BooleanField(default=False)),
                ("partner_management", models.CharField(blank=True, max_length=50)),
                ("referral_tb", models.BooleanField(default=False)),
                ("referral_sti_kp", models.BooleanField(default=False)),
                ("referral_sti_partner", models.BooleanField(default=False)),
                ("referral_general_health", models.BooleanField(default=False)),
                ("referral_hiv_testing", models.BooleanField(default=False)),
                ("referral_mental_health", models.BooleanField(default=False)),
                ("referral_diabetic", models.BooleanField(default=False)),
                ("referral_fp", models.BooleanField(default=False)),
                ("follow_up_due_date", models.DateField(blank=True, null=True)),
                ("follow_up_done_date", models.DateField(blank=True, null=True)),
                ("adr_monitoring", models.BooleanField(default=False)),
                ("prepared_by", models.CharField(blank=True, max_length=200)),
                ("pregnancy_status", models.CharField(blank=True, max_length=50)),
                ("anc_status", models.CharField(blank=True, max_length=50)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinic_visits",
                        to="programs.client",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinic_visits",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="GBVCase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("interview_date", models.DateField(db_index=True)),
                ("incident_date", models.DateField(db_index=True)),
                ("survivor_name", programs.models.gbv.EncryptedCharField(blank=True)),
                (
                    "survivor_contact",
                    programs.models.gbv.EncryptedCharField(blank=True),
                ),
                (
                    "survivor_address",
                    programs.models.gbv.EncryptedCharField(blank=True),
                ),
                (
                    "perpetrator_name",
                    programs.models.gbv.EncryptedCharField(blank=True),
                ),
                (
                    "perpetrator_address",
                    programs.models.gbv.EncryptedCharField(blank=True),
                ),
                (
                    "survivor_age",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "survivor_gender_identity",
                    models.CharField(blank=True, max_length=50),
                ),
                ("survivor_disability", models.BooleanField(default=False)),
                ("gbv_sexual", models.BooleanField(default=False)),
                ("gbv_physical", models.BooleanField(default=False)),
                ("gbv_economic", models.BooleanField(default=False)),
                ("gbv_psychological", models.BooleanField(default=False)),
                ("perpetrator_count", models.PositiveSmallIntegerField(default=1)),
                ("perpetrator_gender", models.CharField(blank=True, max_length=20)),
                (
                    "perpetrator_relationship",
                    models.CharField(blank=True, max_length=100),
                ),
                ("prior_reporting", models.BooleanField(default=False)),
                ("prior_gbv_history", models.BooleanField(default=False)),
                ("needs_medical", models.BooleanField(default=False)),
                ("needs_legal", models.BooleanField(default=False)),
                ("needs_shelter", models.BooleanField(default=False)),
                ("needs_psychosocial", models.BooleanField(default=False)),
                ("local_action_taken", models.TextField(blank=True)),
                ("case_officer_name", models.CharField(blank=True, max_length=200)),
                ("supervisor_name", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gbv_cases",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-incident_date"],
            },
        ),
        migrations.CreateModel(
            name="GBVAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(default="view", max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="programs.gbvcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SafetyHygieneKit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("distribution_date", models.DateField()),
                ("condom_count", models.PositiveIntegerField(default=0)),
                ("condom_demo", models.BooleanField(default=False)),
                ("awareness_session", models.BooleanField(default=False)),
                ("iec_distributed", models.PositiveIntegerField(default=0)),
                ("clinical_service_provided", models.BooleanField(default=False)),
                ("counselling_provided", models.BooleanField(default=False)),
                ("referral_done", models.BooleanField(default=False)),
                ("group_session", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_kits",
                        to="programs.client",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="safety_kits",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-distribution_date"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("referral_date", models.DateField(db_index=True)),
                (
                    "referral_type",
                    models.CharField(
                        choices=[
                            ("art", "ART Enrollment"),
                            ("hiv", "HIV Testing"),
                            ("sti_kp", "STI (KP)"),
                            ("sti_partner", "STI (Partner)"),
                            ("tb", "TB"),
                            ("gbv", "GBV Services"),
                            ("mental_health", "Mental Health"),
                            ("srhr", "SRHR"),
                            ("fp", "Family Planning"),
                            ("general_health", "General Health"),
                            ("hep_c", "Hepatitis C"),
                            ("legal", "Legal Services"),
                            ("shelter", "Shelter"),
                            ("child", "Child Health"),
                            ("maternal", "Maternal Health"),
                            ("diabetic", "Diabetic"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("referral_reason", models.TextField(blank=True)),
                ("referred_to", models.CharField(blank=True, max_length=300)),
                ("referred_by_name", models.CharField(blank=True, max_length=200)),
                (
                    "referred_by_designation",
                    models.CharField(blank=True, max_length=200),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending — awaiting follow-up"),
                            ("linked", "Linked — client reached facility"),
                            ("completed", "Completed — treatment/service received"),
                            ("lost_to_follow_up", "Lost to Follow-Up"),
                            ("refused", "Refused by client"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("outcome_date", models.DateField(blank=True, null=True)),
                ("outcome_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="programs.client",
                    ),
                ),
                (
                    "outcome_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_outcomes_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-referral_date"],
            },
        ),
        migrations.CreateModel(
            name="OutreachSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("session_date", models.DateField(db_index=True)),
                ("peer_educator_name", models.CharField(max_length=200)),
                ("spot_name", models.CharField(blank=True, max_length=200)),
                ("individual_contacts", models.PositiveIntegerField(default=0)),
                ("individual_health_edu_count", models.PositiveIntegerField(default=0)),
                ("group_health_edu_count", models.PositiveIntegerField(default=0)),
                ("condoms_distributed_free", models.PositiveIntegerField(default=0)),
                ("lubricants_distributed_free", models.PositiveIntegerField(default=0)),
                (
                    "iec_bcc_materials_distributed",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "hiv_aids_sti_knowledge_sessions",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("gbv_sessions", models.PositiveSmallIntegerField(default=0)),
                ("referral_mental_health", models.PositiveSmallIntegerField(default=0)),
                (
                    "referral_legal_services",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("referral_htc_hts", models.PositiveSmallIntegerField(default=0)),
                ("referral_gbv", models.PositiveSmallIntegerField(default=0)),
                ("referral_other", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outreach_sessions",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="MobileHealthCamp",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("camp_date", models.DateField(db_index=True)),
                ("location_text", models.CharField(blank=True, max_length=300)),
                ("brothel_name", models.CharField(blank=True, max_length=200)),
                ("clients_served", models.PositiveIntegerField(default=0)),
                ("hiv_tests_done", models.PositiveIntegerField(default=0)),
                ("sti_screenings_done", models.PositiveIntegerField(default=0)),
                ("counselling_sessions", models.PositiveIntegerField(default=0)),
                ("referrals_made", models.PositiveIntegerField(default=0)),
                ("condoms_distributed", models.PositiveIntegerField(default=0)),
                ("services_description", models.TextField(blank=True)),
                ("team_members", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mobile_health_camps",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-camp_date"],
            },
        ),
        migrations.CreateModel(
            name="MHScreening",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "screening_type",
                    models.CharField(
                        choices=[
                            ("depression", "Depression (Zahiruddin Scale)"),
                            ("ptsd", "PTSD"),
                        ],
                        max_length=20,
                    ),
                ),
                ("screening_date", models.DateField(db_index=True)),
                ("psycho_number", models.CharField(blank=True, max_length=50)),
                ("counsellor_name", models.CharField(blank=True, max_length=200)),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "severity_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "No / Minimal"),
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("extreme", "Extreme"),
                            ("profound", "Profound"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_responses", models.JSONField(blank=True, default=dict)),
                ("referred_for_counselling", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mh_screenings",
                        to="programs.client",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mh_screenings",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-screening_date"],
            },
        ),
        migrations.CreateModel(
            name="IndividualCounselling",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("session_date", models.DateField(db_index=True)),
                ("counsellor_name", models.CharField(blank=True, max_length=200)),
                ("issue_sti", models.BooleanField(default=False)),
                ("issue_general_health", models.BooleanField(default=False)),
                ("issue_fp", models.BooleanField(default=False)),
                ("issue_drug_use", models.BooleanField(default=False)),
                ("issue_psychosocial", models.BooleanField(default=False)),
                ("issue_gbv", models.BooleanField(default=False)),
                ("issue_other", models.BooleanField(default=False)),
                ("condom_distributed", models.PositiveSmallIntegerField(default=0)),
                ("iec_materials", models.PositiveSmallIntegerField(default=0)),
                ("referral_mental_health", models.BooleanField(default=False)),
                ("referral_legal", models.BooleanField(default=False)),
                ("referral_htc", models.BooleanField(default=False)),
                ("referral_gbv", models.BooleanField(default=False)),
                ("drug_habit_noted", models.BooleanField(default=False)),
                ("drug_names", models.CharField(blank=True, max_length=300)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counselling_sessions",
                        to="programs.client",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counselling_sessions",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="HTCCounselling",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("pre", "Pre-Test"),
                            ("post", "Post-Test"),
                            ("ongoing", "Ongoing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session_date", models.DateField(db_index=True)),
                (
                    "age_at_session",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("partner_count", models.CharField(blank=True, max_length=20)),
                ("condom_use", models.CharField(blank=True, max_length=20)),
                ("needle_sharing", models.BooleanField(null=True)),
                ("blood_transfusion", models.BooleanField(null=True)),
                ("partner_hiv_positive", models.CharField(blank=True, max_length=20)),
                ("client_pregnant", models.BooleanField(null=True)),
                ("pregnancy_trimester", models.CharField(blank=True, max_length=20)),
                ("covered_hiv_sti_prevention", models.BooleanField(default=False)),
                ("covered_risk_assessment", models.BooleanField(default=False)),
                ("covered_behavior_change", models.BooleanField(default=False)),
                ("covered_support_systems", models.BooleanField(default=False)),
                ("client_consented", models.BooleanField(default=False)),
                ("counsellor_name", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="htc_sessions",
                        to="programs.client",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="htc_sessions",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="HIVSTITestResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("testing_date", models.DateField(db_index=True)),
                ("lab_id", models.CharField(blank=True, max_length=100)),
                (
                    "hiv_result",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("indeterminate", "Indeterminate"),
                            ("not_done", "Not Done"),
                        ],
                        default="not_done",
                        max_length=20,
                    ),
                ),
                (
                    "syphilis_result",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("indeterminate", "Indeterminate"),
                            ("not_done", "Not Done"),
                        ],
                        default="not_done",
                        max_length=20,
                    ),
                ),
                (
                    "hep_b_result",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("indeterminate", "Indeterminate"),
                            ("not_done", "Not Done"),
                        ],
                        default="not_done",
                        max_length=20,
                    ),
                ),
                (
                    "hep_c_result",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("indeterminate", "Indeterminate"),
                            ("not_done", "Not Done"),
                        ],
                        default="not_done",
                        max_length=20,
                    ),
                ),
                ("in_window_period", models.BooleanField(default=False)),
                ("retest_date", models.DateField(blank=True, null=True)),
                ("art_linkage_status", models.CharField(blank=True, max_length=200)),
                ("counsellor_name", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hiv_sti_tests",
                        to="programs.client",
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_results",
                        to="programs.clinicvisit",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hiv_sti_tests",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-testing_date"],
            },
        ),
        migrations.CreateModel(
            name="GroupEducationSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("session_date", models.DateField(db_index=True)),
                ("spot_name", models.CharField(blank=True, max_length=200)),
                ("facilitator_name", models.CharField(blank=True, max_length=200)),
                ("topic", models.CharField(max_length=300)),
                ("participant_count", models.PositiveIntegerField(default=0)),
                ("male_count", models.PositiveIntegerField(default=0)),
                ("female_count", models.PositiveIntegerField(default=0)),
                ("tg_count", models.PositiveIntegerField(default=0)),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("materials_distributed", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_edu_sessions",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="CoordMeeting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("meeting_date", models.DateField(db_index=True)),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("GOB", "GOB / Health Staff"),
                            ("CBO", "CBO / Community Network"),
                            ("internal", "Internal"),
                            ("multi", "Multi-Stakeholder"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("location_text", models.CharField(blank=True, max_length=300)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("participant_count", models.PositiveIntegerField(default=0)),
                ("agenda", models.TextField(blank=True)),
                ("key_decisions", models.TextField(blank=True)),
                ("prepared_by", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coord_meetings",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-meeting_date"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="programs.servicecenter",
            ),
        ),
        migrations.CreateModel(
            name="AutoclaveLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("log_date", models.DateField()),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("autoclave", "Autoclave"),
                            ("incinerator", "Incinerator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("items_autoclaved", models.TextField(blank=True)),
                ("temp_121_achieved", models.BooleanField(null=True)),
                ("tape_test_passed", models.BooleanField(null=True)),
                ("done_by", models.CharField(blank=True, max_length=200)),
                ("material_type", models.CharField(blank=True, max_length=200)),
                ("quantity", models.CharField(blank=True, max_length=100)),
                ("supervised_by", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="autoclave_logs",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-log_date"],
            },
        ),
        migrations.CreateModel(
            name="AntenatalCard",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("visit_date", models.DateField(db_index=True)),
                ("anc_visit_number", models.PositiveSmallIntegerField(default=1)),
                ("trimester", models.CharField(blank=True, max_length=20)),
                ("lmp_date", models.DateField(blank=True, null=True)),
                ("edd", models.DateField(blank=True, null=True)),
                ("blood_pressure", models.CharField(blank=True, max_length=20)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("referred", models.BooleanField(default=False)),
                ("referred_to", models.CharField(blank=True, max_length=200)),
                ("prepared_by", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="antenatal_cards",
                        to="programs.client",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="antenatal_cards",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="ADRRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("report_date", models.DateField()),
                ("drugs_given", models.TextField(blank=True)),
                ("followup_date", models.DateField(blank=True, null=True)),
                ("adverse_effect_present", models.BooleanField(default=False)),
                ("adverse_effect_description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adr_records",
                        to="programs.client",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adr_records",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="StoreRequisition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("requisition_date", models.DateField()),
                ("requirement_date", models.DateField(blank=True, null=True)),
                ("requested_by", models.CharField(max_length=200)),
                (
                    "requested_by_designation",
                    models.CharField(blank=True, max_length=200),
                ),
                ("event_name", models.CharField(blank=True, max_length=300)),
                ("items", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fulfilled", "Fulfilled"),
                            ("partial", "Partially Fulfilled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("fulfilled_by", models.CharField(blank=True, max_length=200)),
                ("fulfillment_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_requisitions",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-requisition_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("event_date", models.DateField(db_index=True)),
                ("event_end_date", models.DateField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("orientation", "Orientation"),
                            ("training", "Training"),
                            ("workshop", "Workshop"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "participant_type",
                    models.CharField(
                        choices=[
                            ("HM", "Health Managers (UHC/DGHS/DGFP)"),
                            ("MW", "Midwives / Medical Assistants"),
                            ("PE", "Peer Educators"),
                            ("CL", "Community Leaders"),
                            ("GOB", "District / Upazila GOB Staff"),
                            ("MIXED", "Mixed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("topic", models.CharField(max_length=300)),
                ("location_text", models.CharField(blank=True, max_length=300)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("total_participants", models.PositiveIntegerField(default=0)),
                ("male_participants", models.PositiveIntegerField(default=0)),
                ("female_participants", models.PositiveIntegerField(default=0)),
                ("tg_participants", models.PositiveIntegerField(default=0)),
                ("facilitator", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_events",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="VisitorRegister",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("visit_date", models.DateField()),
                ("visitor_name", models.CharField(max_length=200)),
                (
                    "designation_and_address",
                    models.CharField(blank=True, max_length=300),
                ),
                ("purpose_of_visit", models.TextField(blank=True)),
                ("iec_bcc_distributed", models.BooleanField(default=False)),
                ("visitor_comments", models.TextField(blank=True)),
                ("prepared_by", models.CharField(blank=True, max_length=200)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visitor_entries",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="StockEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("reporting_month", models.DateField(db_index=True)),
                ("item_name", models.CharField(max_length=200)),
                (
                    "item_category",
                    models.CharField(
                        choices=[
                            ("medicine", "Medicine"),
                            ("contraceptive", "Contraceptive"),
                            ("condom", "Condom / Lubricant"),
                            ("test_kit", "Test Kit"),
                            ("ipc", "IPC / Sterilisation"),
                            ("gbv_dignity", "GBV / Dignity Kit"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("delivery_challan_no", models.CharField(blank=True, max_length=100)),
                ("opening_balance", models.IntegerField(default=0)),
                ("quantity_received", models.IntegerField(default=0)),
                ("quantity_issued", models.IntegerField(default=0)),
                ("quantity_expired_lost", models.IntegerField(default=0)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("APPROVED", "Approved")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_entries",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-reporting_month", "item_name"],
                "unique_together": {("center", "reporting_month", "item_name")},
            },
        ),
        migrations.CreateModel(
            name="TemperatureLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bondhu", "Bondhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("log_date", models.DateField(db_index=True)),
                (
                    "morning_temp_celsius",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                (
                    "afternoon_temp_celsius",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("recorded_by", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="temperature_logs",
                        to="programs.servicecenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-log_date"],
                "unique_together": {("center", "log_date")},
            },
        ),
    ]
