# Generated by Django 5.2.1 on 2026-05-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_client_approval_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adrrecord",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="antenatalcard",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="autoclavelog",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="clinicvisit",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coordmeeting",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gbvcase",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="groupeducationsession",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="hivstitestresult",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="htccounselling",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="individualcounselling",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mhscreening",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mobilehealthcamp",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="outreachsession",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="safetyhygienekit",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="servicecenter",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stockentry",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="storerequisition",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="temperaturelog",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trainingevent",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visitorregister",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
