# Generated by Django 5.2.1 on 2026-05-26 17:26

import programs.models.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0004_meeting_training_upload_gate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordmeeting",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="coord_meetings/photos/%Y/%m/",
                validators=[programs.models.operations.validate_photo_size],
            ),
        ),
        migrations.AlterField(
            model_name="trainingevent",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="training_events/photos/%Y/%m/",
                validators=[programs.models.operations.validate_photo_size],
            ),
        ),
    ]
