# Generated by Django 5.2.1 on 2026-05-27 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        ("programs", "0006_coordmeeting_day_observance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_acid_attack",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_assault",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_beating",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_blackmail",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_confinement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_denied_education",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_denied_inheritance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_denied_work",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_domestic_violence",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_family_rejection",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_forced_gender_identity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_forced_labour",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_forced_pregnancy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_forced_sex_work",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_genital_mutilation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_rape",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_sexual_harassment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_threats",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="gbv_verbal_abuse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="perpetrator_age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gbvcase",
            name="perpetrator_occupation",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="hivstitestresult",
            name="drug_prescribed",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="hivstitestresult",
            name="referred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hivstitestresult",
            name="target_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MSM", "MSM"),
                    ("MSW", "MSW / Kothi"),
                    ("TG", "Transgender / Hijra"),
                    ("FSW", "FSW"),
                    ("OTHERS", "Others"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="hivstitestresult",
            name="test_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HIV", "HIV"),
                    ("SYPHILIS", "Syphilis"),
                    ("HEP_B", "Hepatitis B"),
                    ("HEP_C", "Hepatitis C"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="blood_transplant_history",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="checklist_condom_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="checklist_confidentiality",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="checklist_suicide_risk",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="counseling_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="last_risky_behaviour_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="last_test_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="last_test_result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("positive", "Positive"),
                    ("negative", "Negative"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unmarried", "Unmarried"),
                    ("married", "Married"),
                    ("widowed", "Widowed"),
                    ("divorced", "Divorced"),
                    ("separated", "Separated"),
                    ("cohabiting", "Cohabiting"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="monthly_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="next_revisit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="occupation",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="partner_type",
            field=models.CharField(
                blank=True,
                choices=[("regular", "Regular"), ("irregular", "Irregular")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="previous_test_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="sex_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="sti_history_partner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="sti_history_self",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="tattoo_history",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No"), ("unknown", "Unknown")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="tb_history",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="visit_number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="htccounselling",
            name="window_period_retest_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outreachsession",
            name="manager_endorsement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="outreachsession",
            name="out_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outreachsession",
            name="purpose",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="outreachsession",
            name="return_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outreachsession",
            name="session_variant",
            field=models.CharField(
                choices=[("fixed_site", "Fixed Site"), ("mobile_camp", "Mobile Camp")],
                db_index=True,
                default="fixed_site",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trainingevent",
            name="participants_doctors",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainingevent",
            name="participants_midwives",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainingevent",
            name="participants_nurses",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainingevent",
            name="participants_other",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainingevent",
            name="participants_other_label",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="mhscreening",
            name="severity_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "No / Minimal"),
                    ("minimal", "Minimal"),
                    ("mild", "Mild"),
                    ("moderate", "Moderate"),
                    ("severe", "Severe"),
                    ("extreme", "Extreme"),
                    ("profound", "Profound"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="IECMaterial",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bandhu", "Bandhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("message_board", "Message Board"),
                            ("poster", "Poster"),
                            ("signboard", "Signboard"),
                            ("billboard", "Billboard"),
                            ("digital", "Digital / E-billboard"),
                            ("leaflet", "Leaflet / Flyer"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("date_distributed", models.DateField(db_index=True)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="iec_materials",
                        to="programs.servicecenter",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="iec_materials",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_distributed"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "material_type", "-date_distributed"],
                        name="programs_ie_organis_620940_idx",
                    )
                ],
            },
        ),
    ]
