# Generated by Django 5.2.1 on 2026-06-04 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0010_clinicvisit_phd_fields_gbvcornerrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gbvcornerrecord",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gbvcornerrecord",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gbvcornerrecord",
            name="rejected_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gbvcornerrecord",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gbvcornerrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="gbvcornerrecord",
            name="kobo_submission_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="gbvcornerrecord",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gbvcornerrecord",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gbvcornerrecord",
            name="organisation",
            field=models.CharField(
                choices=[
                    ("PHD", "Partners in Health and Development (PHD)"),
                    ("Bandhu", "Bandhu Social Welfare Society"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gbvcornerrecord",
            name="submitted_by_kobo_user",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
