# Generated by Django 5.2.1 on 2026-06-10 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0015_bandhu_wellness_center_rename"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="nilreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("center__isnull", True)),
                fields=("organisation", "report_date"),
                name="uniq_nil_report_org_day_no_centre",
            ),
        ),
    ]
