# Generated by Django 5.2.1 on 2026-06-17 23:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0016_nilreport_uniq_nil_report_org_day_no_centre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PHDCounsellingReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kobo_submission_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("MANAGER_APPROVED", "Manager approved — awaiting UNFPA"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("manager_approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "submitted_by_kobo_user",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "organisation",
                    models.CharField(
                        choices=[
                            ("PHD", "Partners in Health and Development (PHD)"),
                            ("Bandhu", "Bandhu Social Welfare Society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("report_date", models.DateField(db_index=True)),
                ("prepared_by", models.CharField(blank=True, max_length=200)),
                ("hiv_test_count", models.PositiveIntegerField(default=0)),
                ("sti_count", models.PositiveIntegerField(default=0)),
                ("srhr_count", models.PositiveIntegerField(default=0)),
                ("gbv_count", models.PositiveIntegerField(default=0)),
                ("art_count", models.PositiveIntegerField(default=0)),
                ("mh_count", models.PositiveIntegerField(default=0)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("group_mh_count", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counselling_reports",
                        to="programs.servicecenter",
                    ),
                ),
                (
                    "manager_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
    ]
