# Generated by Django 5.2.1 on 2026-06-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0017_phdcounsellingreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="education_level",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="client",
            name="marital_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="client",
            name="occupation_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
