# Generated by Django 5.2.1 on 2026-06-25 09:29

import programs.models.gbv
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0018_alter_client_education_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="current_address",
            field=programs.models.gbv.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="father_name",
            field=programs.models.gbv.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="mother_name",
            field=programs.models.gbv.EncryptedCharField(blank=True),
        ),
    ]
