# Generated by Django 5.2.1 on 2026-07-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0020_wellnesslogbookentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="awareness",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="client_id_norm",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="clinical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="condom",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="condom_demo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="counseling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="gbv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="group_edu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="htc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="iec",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="legal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="lubricant",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="mental_health",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="recreation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="referral_codes",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="sti_screening",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wellnesslogbookentry",
            name="tg_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
