# Generated by Django 5.2.1 on 2026-08-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0021_wellnesslogbookentry_awareness_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KoboWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_label", models.CharField(db_index=True, max_length=100)),
                ("record_pk", models.CharField(max_length=64)),
                ("kobo_submission_id", models.CharField(db_index=True, max_length=100)),
                ("organisation", models.CharField(blank=True, max_length=50)),
                ("approval_status", models.CharField(blank=True, max_length=20)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("actor", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Kobo withdrawal",
                "ordering": ("-created_at",),
            },
        ),
    ]
