# Generated by Django 5.2.1 on 2026-08-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0022_kobowithdrawal"),
    ]

    operations = [
        migrations.CreateModel(
            name="KoboSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org", models.CharField(blank=True, max_length=50)),
                ("applied", models.BooleanField(default=False)),
                ("candidates", models.PositiveIntegerField(default=0)),
                ("deleted", models.PositiveIntegerField(default=0)),
                ("blocked", models.PositiveIntegerField(default=0)),
                ("live_ids", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Kobo sync run",
                "ordering": ("-created_at",),
            },
        ),
    ]
