# Generated by Django 5.2.1 on 2026-08-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0023_kobosyncrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="kobowithdrawal",
            name="reason",
            field=models.TextField(blank=True),
        ),
    ]
