# Generated by Django 5.2.1 on 2026-08-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0024_kobowithdrawal_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="kobosyncrun",
            name="candidate_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
