"""The form must reject exactly what the engine flags — no more, no less.

Enketo accepts an exclusive option ticked alongside the options it excludes, so
"No concerns" + two concerns reached the data and had to be caught afterwards.
The form now blocks it at entry.

These tests EVALUATE the emitted XPath against selection sets rather than
grepping the string. The string check passed happily while the expression banned
an answer the engine deliberately allows: q2_13 and q2_15 carry TWO negatives
each, and "exclusive AND count-selected > 1" forbade choosing both — turning
q2_15 (3 choices, 2 of them exclusive) into a select_one and refusing an answer
that 9 of 370 Hijra had already given.
"""
import re

from django.test import TestCase

from baseline.anomaly import EXCLUSIVE_CHOICE_CODES
from programs.management.commands.build_baseline_forms import (
    FORMS, _add_other_specify, _enforce_exclusive_choices, _require_all,
)


def _survey(population):
    f = next(x for x in FORMS if population in x['id'])
    choices = f['choices']()
    survey = _require_all(_add_other_specify(f['survey'](), choices))
    return _enforce_exclusive_choices(survey, population, choices), choices


def _passes(expr, selected):
    """Evaluate a constraint expression against a set of selected codes.

    Covers the subset the builder emits: selected(.,'x'), count-selected(.),
    not(), and/or, comparisons.
    """
    py = re.sub(r"selected\(\.,'([^']*)'\)",
                lambda m: str(m.group(1) in selected), expr)
    py = py.replace('count-selected(.)', str(len(selected)))
    py = re.sub(r'\bnot\(', 'not (', py)
    return eval(py)  # noqa: S307 — expression is generated by this repo


class ExclusiveChoiceConstraintTest(TestCase):
    def test_every_exclusive_field_gets_a_constraint_and_a_message(self):
        for population, fields in EXCLUSIVE_CHOICE_CODES.items():
            survey, _ = _survey(population)
            by_name = {r[1]: r for r in survey}
            for field in fields:
                row = by_name[field]
                self.assertTrue(row[7], f'{population}/{field} has no constraint')
                self.assertTrue(row[8], f'{population}/{field} has no message')

    def test_truth_table_matches_the_engine_rule(self):
        """The engine flags exclusive + NON-exclusive. The form must reject that and
        nothing else: any single answer passes, an exclusive with a real option
        fails, two real options pass, and two exclusives together pass — hedging
        between two negatives is not a data conflict (anomaly.py documents this,
        and the engine has never flagged it)."""
        for population, fields in EXCLUSIVE_CHOICE_CODES.items():
            survey, choices = _survey(population)
            by_name = {r[1]: r for r in survey}
            for field, codes in fields.items():
                row = by_name[field]
                expr, where = row[7], f'{population}/{field}'
                listname = (row[0] or '').split()[-1]
                all_codes = [str(c[1]) for c in choices if c[0] == listname]
                others = [c for c in all_codes if c not in codes]

                for c in all_codes:
                    self.assertTrue(_passes(expr, {c}), f'{where}: {c} alone rejected')

                for c in codes:
                    self.assertFalse(_passes(expr, {c, others[0]}),
                                     f'{where}: {c}+{others[0]} accepted')

                if len(others) > 1:
                    self.assertTrue(_passes(expr, {others[0], others[1]}),
                                    f'{where}: two non-exclusive options rejected')

                if len(codes) > 1:
                    self.assertTrue(_passes(expr, set(codes)),
                                    f'{where}: two exclusives rejected — the engine '
                                    'allows this, so the form must too')

    def test_codes_exist_in_the_choice_list(self):
        # A code that is not in the list compiles fine and silently never fires.
        for population, fields in EXCLUSIVE_CHOICE_CODES.items():
            survey, choices = _survey(population)
            by_name = {r[1]: r for r in survey}
            for field, codes in fields.items():
                lst = (by_name[field][0] or '').split()[-1]
                names = {str(c[1]) for c in choices if c[0] == lst}
                for c in codes:
                    self.assertIn(c, names, f'{population}/{field}: {c} not in {lst}')

    def test_existing_constraint_is_kept(self):
        # Q9.5 caps the answer at five services; the exclusive pass must AND onto
        # that, never replace it.
        survey, _ = _survey('fsw')
        q9_5 = next(r for r in survey if r[1] == 'q9_5')
        self.assertIn('count-selected(.) <= 5', q9_5[7])

    def test_a_missing_field_fails_loudly(self):
        with self.assertRaises(ValueError):
            _enforce_exclusive_choices([['select_multiple x', 'unrelated'] + [''] * 10],
                                       'fsw', [])

    def test_an_all_exclusive_question_fails_loudly(self):
        # Every choice exclusive => unanswerable. Break the build rather than
        # deploy a question nobody can complete.
        survey = [['select_multiple lst', 'q9_6'] + [''] * 10]
        with self.assertRaises(ValueError):
            _enforce_exclusive_choices(survey, 'fsw', [('lst', '10', 'No concerns', '')])
