# Generated by Django 5.2.1 on 2026-05-23 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("partner", models.CharField(blank=True, db_index=True, max_length=20)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("below_target", "Below Target"),
                            ("anomaly", "Anomaly Detected"),
                            ("overdue_cases", "Overdue Cases"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("acknowledged", models.BooleanField(db_index=True, default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["partner", "acknowledged"],
                        name="tracker_ale_partner_5d019a_idx",
                    ),
                    models.Index(
                        fields=["severity", "acknowledged"],
                        name="tracker_ale_severit_c899c5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthlyTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("partner", models.CharField(db_index=True, max_length=20)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("mpdsr", "MPDSR"),
                            ("fistula", "Fistula Campaign"),
                            ("activity", "Activity Report"),
                            ("baseline", "Baseline/Endline Survey"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("target", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "partner"],
                "indexes": [
                    models.Index(
                        fields=["partner", "year", "month"],
                        name="tracker_mon_partner_efa566_idx",
                    )
                ],
                "unique_together": {("partner", "form_type", "year", "month")},
            },
        ),
    ]
