# Generated by Django 5.2.1 on 2026-05-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alerttype_submission_gap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("below_target", "Below Target"),
                    ("anomaly", "Anomaly Detected"),
                    ("overdue_cases", "Overdue Cases"),
                    ("submission_gap", "48-Hour Submission Gap"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="monthlytarget",
            name="form_type",
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
