# Generated by Django 5.2.1 on 2026-06-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_extend_form_type_for_programs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("below_target", "Below Target"),
                    ("anomaly", "Anomaly Detected"),
                    ("overdue_cases", "Overdue Cases"),
                    ("submission_gap", "48-Hour Submission Gap"),
                    ("daily_silence", "No Daily Report"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
