# Generated by Django 5.2.1 on 2026-05-23 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("partner", models.CharField(db_index=True, max_length=20)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("topic", models.CharField(max_length=300)),
                ("facilitator", models.CharField(blank=True, max_length=200)),
                ("date", models.DateField(db_index=True)),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("expected_participants", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("participant_name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("community_worker", "Community Worker"),
                            ("supervisor", "Supervisor"),
                            ("health_staff", "Health Staff"),
                            ("other", "Other"),
                        ],
                        default="community_worker",
                        max_length=30,
                    ),
                ),
                ("attended", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="training.trainingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["participant_name"],
            },
        ),
        migrations.AddIndex(
            model_name="trainingsession",
            index=models.Index(
                fields=["partner", "date"], name="training_tr_partner_0ee192_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingattendance",
            unique_together={("session", "participant_name")},
        ),
    ]
